// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TulingMessage.proto

package com.tuling.protocolbuffdemo.proto;

public final class TulingMessages {
  private TulingMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MyClassesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tuling_messages.MyClasses)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 class_id = 1;</code>
     */
    boolean hasClassId();
    /**
     * <code>required int64 class_id = 1;</code>
     */
    long getClassId();

    /**
     * <code>optional string class_name = 2;</code>
     */
    boolean hasClassName();
    /**
     * <code>optional string class_name = 2;</code>
     */
    java.lang.String getClassName();
    /**
     * <code>optional string class_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getClassNameBytes();

    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    java.util.List<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student> 
        getClassStudentsList();
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student getClassStudents(int index);
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    int getClassStudentsCount();
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    java.util.List<? extends com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder> 
        getClassStudentsOrBuilderList();
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder getClassStudentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code tuling_messages.MyClasses}
   */
  public  static final class MyClasses extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tuling_messages.MyClasses)
      MyClassesOrBuilder {
    // Use MyClasses.newBuilder() to construct.
    private MyClasses(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MyClasses() {
      classId_ = 0L;
      className_ = "";
      classStudents_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyClasses(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              classId_ = input.readInt64();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              className_ = bs;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                classStudents_ = new java.util.ArrayList<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student>();
                mutable_bitField0_ |= 0x00000004;
              }
              classStudents_.add(input.readMessage(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          classStudents_ = java.util.Collections.unmodifiableList(classStudents_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.class, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Builder.class);
    }

    /**
     * Protobuf enum {@code tuling_messages.MyClasses.Gender}
     */
    public enum Gender
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>MALE = 0;</code>
       */
      MALE(0, 0),
      /**
       * <code>FEMALE = 1;</code>
       */
      FEMALE(1, 1),
      ;

      /**
       * <code>MALE = 0;</code>
       */
      public static final int MALE_VALUE = 0;
      /**
       * <code>FEMALE = 1;</code>
       */
      public static final int FEMALE_VALUE = 1;


      public final int getNumber() {
        return value;
      }

      public static Gender valueOf(int value) {
        switch (value) {
          case 0: return MALE;
          case 1: return FEMALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gender>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gender> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gender>() {
              public Gender findValueByNumber(int number) {
                return Gender.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gender[] VALUES = values();

      public static Gender valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Gender(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:tuling_messages.MyClasses.Gender)
    }

    public interface StudentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tuling_messages.MyClasses.Student)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int64 student_id = 1;</code>
       */
      boolean hasStudentId();
      /**
       * <code>required int64 student_id = 1;</code>
       */
      long getStudentId();

      /**
       * <code>required string student_name = 2;</code>
       */
      boolean hasStudentName();
      /**
       * <code>required string student_name = 2;</code>
       */
      java.lang.String getStudentName();
      /**
       * <code>required string student_name = 2;</code>
       */
      com.google.protobuf.ByteString
          getStudentNameBytes();

      /**
       * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
       */
      boolean hasStudentGender();
      /**
       * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
       */
      com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender getStudentGender();

      /**
       * <code>optional int32 student_age = 4;</code>
       */
      boolean hasStudentAge();
      /**
       * <code>optional int32 student_age = 4;</code>
       */
      int getStudentAge();
    }
    /**
     * Protobuf type {@code tuling_messages.MyClasses.Student}
     */
    public  static final class Student extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:tuling_messages.MyClasses.Student)
        StudentOrBuilder {
      // Use Student.newBuilder() to construct.
      private Student(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private Student() {
        studentId_ = 0L;
        studentName_ = "";
        studentGender_ = 0;
        studentAge_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Student(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                studentId_ = input.readInt64();
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                studentName_ = bs;
                break;
              }
              case 24: {
                int rawValue = input.readEnum();
                com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender value = com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(3, rawValue);
                } else {
                  bitField0_ |= 0x00000004;
                  studentGender_ = rawValue;
                }
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                studentAge_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_Student_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.class, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder.class);
      }

      private int bitField0_;
      public static final int STUDENT_ID_FIELD_NUMBER = 1;
      private long studentId_;
      /**
       * <code>required int64 student_id = 1;</code>
       */
      public boolean hasStudentId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 student_id = 1;</code>
       */
      public long getStudentId() {
        return studentId_;
      }

      public static final int STUDENT_NAME_FIELD_NUMBER = 2;
      private volatile java.lang.Object studentName_;
      /**
       * <code>required string student_name = 2;</code>
       */
      public boolean hasStudentName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string student_name = 2;</code>
       */
      public java.lang.String getStudentName() {
        java.lang.Object ref = studentName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            studentName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string student_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStudentNameBytes() {
        java.lang.Object ref = studentName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          studentName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STUDENT_GENDER_FIELD_NUMBER = 3;
      private int studentGender_;
      /**
       * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
       */
      public boolean hasStudentGender() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
       */
      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender getStudentGender() {
        com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender result = com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender.valueOf(studentGender_);
        return result == null ? com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender.MALE : result;
      }

      public static final int STUDENT_AGE_FIELD_NUMBER = 4;
      private int studentAge_;
      /**
       * <code>optional int32 student_age = 4;</code>
       */
      public boolean hasStudentAge() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 student_age = 4;</code>
       */
      public int getStudentAge() {
        return studentAge_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasStudentId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasStudentName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, studentId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, studentName_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeEnum(3, studentGender_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, studentAge_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, studentId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, studentName_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(3, studentGender_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, studentAge_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tuling_messages.MyClasses.Student}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tuling_messages.MyClasses.Student)
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_Student_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_Student_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.class, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder.class);
        }

        // Construct using com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          studentId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          studentName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          studentGender_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          studentAge_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_Student_descriptor;
        }

        public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student getDefaultInstanceForType() {
          return com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.getDefaultInstance();
        }

        public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student build() {
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student buildPartial() {
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student result = new com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.studentId_ = studentId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.studentName_ = studentName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.studentGender_ = studentGender_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.studentAge_ = studentAge_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student) {
            return mergeFrom((com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student other) {
          if (other == com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.getDefaultInstance()) return this;
          if (other.hasStudentId()) {
            setStudentId(other.getStudentId());
          }
          if (other.hasStudentName()) {
            bitField0_ |= 0x00000002;
            studentName_ = other.studentName_;
            onChanged();
          }
          if (other.hasStudentGender()) {
            setStudentGender(other.getStudentGender());
          }
          if (other.hasStudentAge()) {
            setStudentAge(other.getStudentAge());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasStudentId()) {
            return false;
          }
          if (!hasStudentName()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long studentId_ ;
        /**
         * <code>required int64 student_id = 1;</code>
         */
        public boolean hasStudentId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 student_id = 1;</code>
         */
        public long getStudentId() {
          return studentId_;
        }
        /**
         * <code>required int64 student_id = 1;</code>
         */
        public Builder setStudentId(long value) {
          bitField0_ |= 0x00000001;
          studentId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 student_id = 1;</code>
         */
        public Builder clearStudentId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          studentId_ = 0L;
          onChanged();
          return this;
        }

        private java.lang.Object studentName_ = "";
        /**
         * <code>required string student_name = 2;</code>
         */
        public boolean hasStudentName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string student_name = 2;</code>
         */
        public java.lang.String getStudentName() {
          java.lang.Object ref = studentName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              studentName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string student_name = 2;</code>
         */
        public com.google.protobuf.ByteString
            getStudentNameBytes() {
          java.lang.Object ref = studentName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            studentName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string student_name = 2;</code>
         */
        public Builder setStudentName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          studentName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string student_name = 2;</code>
         */
        public Builder clearStudentName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          studentName_ = getDefaultInstance().getStudentName();
          onChanged();
          return this;
        }
        /**
         * <code>required string student_name = 2;</code>
         */
        public Builder setStudentNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          studentName_ = value;
          onChanged();
          return this;
        }

        private int studentGender_ = 0;
        /**
         * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
         */
        public boolean hasStudentGender() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
         */
        public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender getStudentGender() {
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender result = com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender.valueOf(studentGender_);
          return result == null ? com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender.MALE : result;
        }
        /**
         * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
         */
        public Builder setStudentGender(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Gender value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          studentGender_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>optional .tuling_messages.MyClasses.Gender student_gender = 3;</code>
         */
        public Builder clearStudentGender() {
          bitField0_ = (bitField0_ & ~0x00000004);
          studentGender_ = 0;
          onChanged();
          return this;
        }

        private int studentAge_ ;
        /**
         * <code>optional int32 student_age = 4;</code>
         */
        public boolean hasStudentAge() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 student_age = 4;</code>
         */
        public int getStudentAge() {
          return studentAge_;
        }
        /**
         * <code>optional int32 student_age = 4;</code>
         */
        public Builder setStudentAge(int value) {
          bitField0_ |= 0x00000008;
          studentAge_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 student_age = 4;</code>
         */
        public Builder clearStudentAge() {
          bitField0_ = (bitField0_ & ~0x00000008);
          studentAge_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:tuling_messages.MyClasses.Student)
      }

      // @@protoc_insertion_point(class_scope:tuling_messages.MyClasses.Student)
      private static final com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student();
      }

      public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<Student>
          PARSER = new com.google.protobuf.AbstractParser<Student>() {
        public Student parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new Student(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<Student> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Student> getParserForType() {
        return PARSER;
      }

      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int CLASS_ID_FIELD_NUMBER = 1;
    private long classId_;
    /**
     * <code>required int64 class_id = 1;</code>
     */
    public boolean hasClassId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 class_id = 1;</code>
     */
    public long getClassId() {
      return classId_;
    }

    public static final int CLASS_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object className_;
    /**
     * <code>optional string class_name = 2;</code>
     */
    public boolean hasClassName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string class_name = 2;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          className_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string class_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLASS_STUDENTS_FIELD_NUMBER = 3;
    private java.util.List<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student> classStudents_;
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    public java.util.List<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student> getClassStudentsList() {
      return classStudents_;
    }
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    public java.util.List<? extends com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder> 
        getClassStudentsOrBuilderList() {
      return classStudents_;
    }
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    public int getClassStudentsCount() {
      return classStudents_.size();
    }
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student getClassStudents(int index) {
      return classStudents_.get(index);
    }
    /**
     * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
     */
    public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder getClassStudentsOrBuilder(
        int index) {
      return classStudents_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClassId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getClassStudentsCount(); i++) {
        if (!getClassStudents(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, classId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, className_);
      }
      for (int i = 0; i < classStudents_.size(); i++) {
        output.writeMessage(3, classStudents_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, classId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, className_);
      }
      for (int i = 0; i < classStudents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, classStudents_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input);}
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseDelimitedWithIOException(PARSER, input, extensionRegistry);}
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input);}
    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage.parseWithIOException(PARSER, input, extensionRegistry);}

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tuling_messages.MyClasses}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tuling_messages.MyClasses)
        com.tuling.protocolbuffdemo.proto.TulingMessages.MyClassesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.class, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Builder.class);
      }

      // Construct using com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getClassStudentsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        classId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        className_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (classStudentsBuilder_ == null) {
          classStudents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          classStudentsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.internal_static_tuling_messages_MyClasses_descriptor;
      }

      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses getDefaultInstanceForType() {
        return com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.getDefaultInstance();
      }

      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses build() {
        com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses buildPartial() {
        com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses result = new com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.classId_ = classId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.className_ = className_;
        if (classStudentsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            classStudents_ = java.util.Collections.unmodifiableList(classStudents_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.classStudents_ = classStudents_;
        } else {
          result.classStudents_ = classStudentsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses) {
          return mergeFrom((com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses other) {
        if (other == com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.getDefaultInstance()) return this;
        if (other.hasClassId()) {
          setClassId(other.getClassId());
        }
        if (other.hasClassName()) {
          bitField0_ |= 0x00000002;
          className_ = other.className_;
          onChanged();
        }
        if (classStudentsBuilder_ == null) {
          if (!other.classStudents_.isEmpty()) {
            if (classStudents_.isEmpty()) {
              classStudents_ = other.classStudents_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureClassStudentsIsMutable();
              classStudents_.addAll(other.classStudents_);
            }
            onChanged();
          }
        } else {
          if (!other.classStudents_.isEmpty()) {
            if (classStudentsBuilder_.isEmpty()) {
              classStudentsBuilder_.dispose();
              classStudentsBuilder_ = null;
              classStudents_ = other.classStudents_;
              bitField0_ = (bitField0_ & ~0x00000004);
              classStudentsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getClassStudentsFieldBuilder() : null;
            } else {
              classStudentsBuilder_.addAllMessages(other.classStudents_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClassId()) {
          return false;
        }
        for (int i = 0; i < getClassStudentsCount(); i++) {
          if (!getClassStudents(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long classId_ ;
      /**
       * <code>required int64 class_id = 1;</code>
       */
      public boolean hasClassId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 class_id = 1;</code>
       */
      public long getClassId() {
        return classId_;
      }
      /**
       * <code>required int64 class_id = 1;</code>
       */
      public Builder setClassId(long value) {
        bitField0_ |= 0x00000001;
        classId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 class_id = 1;</code>
       */
      public Builder clearClassId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        classId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object className_ = "";
      /**
       * <code>optional string class_name = 2;</code>
       */
      public boolean hasClassName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string class_name = 2;</code>
       */
      public java.lang.String getClassName() {
        java.lang.Object ref = className_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            className_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string class_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getClassNameBytes() {
        java.lang.Object ref = className_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          className_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string class_name = 2;</code>
       */
      public Builder setClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        className_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string class_name = 2;</code>
       */
      public Builder clearClassName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        className_ = getDefaultInstance().getClassName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string class_name = 2;</code>
       */
      public Builder setClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        className_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student> classStudents_ =
        java.util.Collections.emptyList();
      private void ensureClassStudentsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          classStudents_ = new java.util.ArrayList<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student>(classStudents_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder> classStudentsBuilder_;

      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public java.util.List<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student> getClassStudentsList() {
        if (classStudentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(classStudents_);
        } else {
          return classStudentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public int getClassStudentsCount() {
        if (classStudentsBuilder_ == null) {
          return classStudents_.size();
        } else {
          return classStudentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student getClassStudents(int index) {
        if (classStudentsBuilder_ == null) {
          return classStudents_.get(index);
        } else {
          return classStudentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder setClassStudents(
          int index, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student value) {
        if (classStudentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassStudentsIsMutable();
          classStudents_.set(index, value);
          onChanged();
        } else {
          classStudentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder setClassStudents(
          int index, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder builderForValue) {
        if (classStudentsBuilder_ == null) {
          ensureClassStudentsIsMutable();
          classStudents_.set(index, builderForValue.build());
          onChanged();
        } else {
          classStudentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder addClassStudents(com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student value) {
        if (classStudentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassStudentsIsMutable();
          classStudents_.add(value);
          onChanged();
        } else {
          classStudentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder addClassStudents(
          int index, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student value) {
        if (classStudentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureClassStudentsIsMutable();
          classStudents_.add(index, value);
          onChanged();
        } else {
          classStudentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder addClassStudents(
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder builderForValue) {
        if (classStudentsBuilder_ == null) {
          ensureClassStudentsIsMutable();
          classStudents_.add(builderForValue.build());
          onChanged();
        } else {
          classStudentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder addClassStudents(
          int index, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder builderForValue) {
        if (classStudentsBuilder_ == null) {
          ensureClassStudentsIsMutable();
          classStudents_.add(index, builderForValue.build());
          onChanged();
        } else {
          classStudentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder addAllClassStudents(
          java.lang.Iterable<? extends com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student> values) {
        if (classStudentsBuilder_ == null) {
          ensureClassStudentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, classStudents_);
          onChanged();
        } else {
          classStudentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder clearClassStudents() {
        if (classStudentsBuilder_ == null) {
          classStudents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          classStudentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public Builder removeClassStudents(int index) {
        if (classStudentsBuilder_ == null) {
          ensureClassStudentsIsMutable();
          classStudents_.remove(index);
          onChanged();
        } else {
          classStudentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder getClassStudentsBuilder(
          int index) {
        return getClassStudentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder getClassStudentsOrBuilder(
          int index) {
        if (classStudentsBuilder_ == null) {
          return classStudents_.get(index);  } else {
          return classStudentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public java.util.List<? extends com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder> 
           getClassStudentsOrBuilderList() {
        if (classStudentsBuilder_ != null) {
          return classStudentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(classStudents_);
        }
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder addClassStudentsBuilder() {
        return getClassStudentsFieldBuilder().addBuilder(
            com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder addClassStudentsBuilder(
          int index) {
        return getClassStudentsFieldBuilder().addBuilder(
            index, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.getDefaultInstance());
      }
      /**
       * <code>repeated .tuling_messages.MyClasses.Student class_students = 3;</code>
       */
      public java.util.List<com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder> 
           getClassStudentsBuilderList() {
        return getClassStudentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder> 
          getClassStudentsFieldBuilder() {
        if (classStudentsBuilder_ == null) {
          classStudentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.Student.Builder, com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses.StudentOrBuilder>(
                  classStudents_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          classStudents_ = null;
        }
        return classStudentsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:tuling_messages.MyClasses)
    }

    // @@protoc_insertion_point(class_scope:tuling_messages.MyClasses)
    private static final com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses();
    }

    public static com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<MyClasses>
        PARSER = new com.google.protobuf.AbstractParser<MyClasses>() {
      public MyClasses parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new MyClasses(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<MyClasses> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MyClasses> getParserForType() {
      return PARSER;
    }

    public com.tuling.protocolbuffdemo.proto.TulingMessages.MyClasses getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tuling_messages_MyClasses_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tuling_messages_MyClasses_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tuling_messages_MyClasses_Student_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tuling_messages_MyClasses_Student_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023TulingMessage.proto\022\017tuling_messages\"\223" +
      "\002\n\tMyClasses\022\020\n\010class_id\030\001 \002(\003\022\022\n\nclass_" +
      "name\030\002 \001(\t\022:\n\016class_students\030\003 \003(\0132\".tul" +
      "ing_messages.MyClasses.Student\032\203\001\n\007Stude" +
      "nt\022\022\n\nstudent_id\030\001 \002(\003\022\024\n\014student_name\030\002" +
      " \002(\t\0229\n\016student_gender\030\003 \001(\0162!.tuling_me" +
      "ssages.MyClasses.Gender\022\023\n\013student_age\030\004" +
      " \001(\005\"\036\n\006Gender\022\010\n\004MALE\020\000\022\n\n\006FEMALE\020\001B3\n!" +
      "com.tuling.protocolbuffdemo.protoB\016Tulin" +
      "gMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tuling_messages_MyClasses_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tuling_messages_MyClasses_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tuling_messages_MyClasses_descriptor,
        new java.lang.String[] { "ClassId", "ClassName", "ClassStudents", });
    internal_static_tuling_messages_MyClasses_Student_descriptor =
      internal_static_tuling_messages_MyClasses_descriptor.getNestedTypes().get(0);
    internal_static_tuling_messages_MyClasses_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tuling_messages_MyClasses_Student_descriptor,
        new java.lang.String[] { "StudentId", "StudentName", "StudentGender", "StudentAge", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
